### ISSUE TITLE
Index operation failed

### ISSUE THREAD

**Issue by DrDoHicky** [gavsto/AutomateAPI#45] opened 2020-10-27 20:21 UTC
Trying to run the command `Get-AutomateComputer -Online $False | Compare-AutomateControlStatus`

![image](https://user-images.githubusercontent.com/39975114/97357454-2e78bb00-1870-11eb-9cf2-4d3c0b2a060a.png)

I used `Connect-AutomateAPI` and `Connect-ControlAPI` before. Verified that I have the correct monitor in Automate.

**Comment by WhAtEvErYoUmEaN** [comment] 2020-11-05 10:38
I have the same issue upon using `Get-AutomateComputer -Online $False | Compare-AutomateControlStatus`

![Screenshot](https://user-images.githubusercontent.com/7109098/98230268-411f7e00-1f5b-11eb-945f-31dbbabe095e.png)

Coincidentally Automate can currently not connect to the control API according to the Dashboard. @DrDoHicky can you confirm that?

**Comment by WhAtEvErYoUmEaN** [comment] 2020-11-05 11:06
![grafik](https://user-images.githubusercontent.com/7109098/98233425-50a0c600-1f5f-11eb-8bec-94e4cb7c7258.png)
Looks like the issue resides on Control.
Reinstalling the Automate Plugin did nothing so far.

**Comment by gavsto** [comment] 2020-11-05 13:26
I have confirmed this is a bug, it seems the latest version of Control requires an anti-forgery token. Need to do more investigation on this, DarrenDK posted this up as he'd highlighted a similiar issue with Immybot:

private string _antiForgeryToken;
    private async Task RefreshAntiForgeryToken()
    {
      var antiForgeryResponse = await _client.GetStringAsync("/");
      var matchGroups = Regex.Match(antiForgeryResponse, @"\""antiForgeryToken""\:\""(.+?)\""")?.Groups;      
      if (matchGroups?.Count > 0)
      {
        _antiForgeryToken = matchGroups[1].Value;
      }
    }
    private async Task<HttpResponseMessage> Post(string route, StringContent content, CancellationToken token)
    {
      var updatedRoute = ReplaceExtensionId(route);
      content.Headers.Add(ApiKeyHeader, Helpers.GetApiToken(_extensionApiKey));
      await RefreshAntiForgeryToken();
      content.Headers.Add("X-Anti-Forgery-Token", _antiForgeryToken);
      var res =  await _client.PostAsync(updatedRoute, content, token);
      var data = await res.Content.ReadAsStringAsync();
      if (data.Contains("Invalid anti-forgery token"))
      {
        await RefreshAntiForgeryToken();
      }
      return res;
    }

This is going to require a bit of time to fix.

**Comment by DarrenWhite99** [comment] 2020-12-08 09:21
This has been addressed in the large commit today.
Referencing this issue in a branch pull request #53 so that this issue can be closed when the pull is finalized.

**Comment by codepend** [comment] 2020-12-14 19:07
Hello,
I believe this still may be an issue, or Control the system I am trying against is too old a version? (20.11.1622.7619)
According to fiddler, when calling: 

https://control.somedomain.com/App_Extensions/fc234f0e-2e8e-4a1f-b977-ba41b14031f7/ReportService.ashx/GenerateReportForAutomate

Getting an unauthorized response, with a message of: Invalid anti-forgery token.

**Comment by DarrenWhite99** [comment] 2020-12-17 09:43
Make sure that you have the latest from the master branch.
Actually, you might want to pull from the FixVerify branch, since that is where I am developing/troubleshooting/fixing from.

**Closed** 2021-09-01 01:29 UTC
